### ISSUE TITLE
Seems to be missing TV1/2/3

### ISSUE THREAD

**Issue by kiwijunglist** [Fruityski/Plex-Live-TV-DVR-with-no-TV-tuner-or-aerial#1]
Hi

I seem to be missing TV ONE / TWO / THREE 

I setup tellytv as per the following:

**Docker-Compose**

```
  tellytv:
    container_name: tellytv
    image: tellytv/telly:dev-ffmpeg
    ports:
      - 6077:6077
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Pacific/Auckland
    volumes:
      - /home/mike/docker/config/tellytv/telly.config.toml:/etc/telly/telly.config.toml
    restart: unless-stopped
```

**TellyTV configuration**

```
##### telly.config.toml ####

[Discovery]                                    
  Device-Auth = "telly123"                     
  Device-ID = 12345678                         
  Device-UUID = ""
  Device-Firmware-Name = "hdhomeruntc_atsc"
  Device-Firmware-Version = "20150826"
  Device-Friendly-Name = "telly"
  Device-Manufacturer = "Silicondust"
  Device-Model-Number = "HDTC-2US"
  SSDP = true

[IPTV]
  Streams = 3
  Starting-Channel = 1
  XMLTV-Channels = true

### FFMpeg is enabled ### 
  FFMpeg = true             

[Log]
  Level = "warn"
  Requests = false

[Web]
  Base-Address = "192.168.1.99:6077"
  Listen-Address = "0.0.0.0:6077"

[[Source]]
  Name = "FreeviewNZ"
  Provider = "Custom"
  M3U = "http://i.mjh.nz/nz/raw-tv.m3u8"
  Filter = ""
  FilterKey = ""
  FilterRaw = false
  Sort = ""
```

**Plex setup:**

![image](https://user-images.githubusercontent.com/1858199/141025908-911c09bf-9088-4bad-b35c-1b21dc7e0b02.png)

![image](https://user-images.githubusercontent.com/1858199/141025966-2de04778-5bc6-4538-8356-ac9674367ef3.png)

![image](https://user-images.githubusercontent.com/1858199/141026019-0ead6fcb-6f8a-49d1-bd7f-5056556c4743.png)
